<?php
if (!defined('ABSPATH')) exit;
get_header();
if (have_posts()) { the_post(); }
if (cg_elementor_is_built(get_the_ID())) :
?>
<main id="primary" class="site-main elementor-front-page"><?php the_content(); ?></main>
<?php else: $hero=get_theme_mod('cg_hero_image'); ?>

<section class="hero"><div class="container"><div class="hero-copy"><div class="eyebrow">Цветы с доставкой</div><h1><?php echo esc_html(get_theme_mod('cg_hero_title','Дарите эмоции вместе с цветами')); ?></h1><p><?php echo esc_html(get_theme_mod('cg_hero_text','Свежие цветы, стильные букеты и быстрая доставка по Нововоронежу и Воронежской области.')); ?></p><div class="hero-actions"><a class="button" href="<?php echo esc_url(cg_catalog_url()); ?>"><?php echo esc_html(get_theme_mod('cg_hero_button','Смотреть каталог')); ?></a><a class="button button--ghost" href="#popular">Популярные букеты</a></div></div><div class="hero-art" style="background-image:linear-gradient(90deg,rgba(255,253,250,.45),rgba(255,255,255,0)),url('<?php echo esc_url($hero ?: get_template_directory_uri().'/assets/images/hero-placeholder.svg'); ?>')"></div></div></section>
<section class="benefits"><div class="container benefits-grid"><div class="benefit"><div class="benefit-icon">🌷</div><div><strong>Свежие цветы</strong><span>Поставка и сборка каждый день</span></div></div><div class="benefit"><div class="benefit-icon">🚚</div><div><strong>Быстрая доставка</strong><span>Нововоронеж и область</span></div></div><div class="benefit"><div class="benefit-icon">🛡</div><div><strong>Гарантия качества</strong><span>Фото букета перед отправкой</span></div></div><div class="benefit"><div class="benefit-icon">🎁</div><div><strong>Открытка в подарок</strong><span>Добавим ваши тёплые слова</span></div></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><h2 class="section-title">Выберите повод</h2><div class="section-subtitle">Категории уже подготовлены — товары подтянутся из WooCommerce.</div></div><a class="text-link" href="<?php echo esc_url(cg_catalog_url()); ?>">Весь каталог →</a></div><div class="category-grid"><?php $cats=[['Свадебные','svadebnye'],['Сладкие','sladkie'],['Авторские','avtorskie'],['Lux','lux'],['До 2000','do-2000'],['До 5000','do-5000'],['До 10000','do-10000'],['Все букеты','']]; foreach($cats as $c): ?><a class="category-card" href="<?php echo esc_url($c[1]?home_url('/product-category/'.$c[1].'/'):cg_catalog_url()); ?>"><h3><?php echo esc_html($c[0]); ?></h3><span>Смотреть товары →</span></a><?php endforeach; ?></div></div></section>
<section class="section section--soft" id="popular"><div class="container"><div class="section-head"><div><h2 class="section-title">Популярные букеты</h2><div class="section-subtitle">Хиты продаж и свежие композиции.</div></div><a class="text-link" href="<?php echo esc_url(cg_catalog_url()); ?>">Смотреть все →</a></div><?php if(shortcode_exists('products')) echo do_shortcode('[products limit="8" columns="4" orderby="popularity"]'); else echo '<p>Установите и активируйте WooCommerce.</p>'; ?></div></section>
<section class="section"><div class="container"><div class="about-grid"><div class="about-copy"><div class="eyebrow">О нас</div><h2>Мы создаём букеты, которые говорят за вас</h2><p>Каждый букет — это забота, вдохновение и внимание к деталям. Мы бережно собираем композиции и доставляем их по Нововоронежу и Воронежской области.</p><a class="button" href="<?php echo esc_url(home_url('/about/')); ?>">Подробнее о нас</a></div><div class="about-image"></div></div></div></section>
<section class="section"><div class="container"><div class="newsletter"><div><h2>Скидка 10% на первый заказ</h2><p>Оставьте e-mail и получите промокод. Форму можно подключить к Contact Form 7 или Fluent Forms.</p></div><form action="#" method="post"><input type="email" placeholder="Ваш e-mail" aria-label="Ваш e-mail"><button class="button" type="submit">Получить промокод</button></form></div></div></section>
<?php endif; get_footer(); ?>
